openapi: '3.0.0'
info:
  title: kytos/flow_manager
  version: 1.1.0
  description: >-
    **Warning**: *This documentation is experimental and may change soon.*


    Manages flows for OpenFlow switches, for version 1.3. Can add, list
    and remove flows from datapaths. Currently supports a subset of available
    matches and actions from the OpenFlow specification.
tags:
  - name: List
  - name: Add
  - name: Delete
paths:
  /api/kytos/flow_manager/v2/flows:
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from all known datapaths.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
        '404':
          description: Switch ID not found.
    post:
      tags:
        - Add
      summary: Insert flows in all known datapaths.
      requestBody:
        description: List of flows to be inserted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      responses:
        '202':
           description: FlowMod messages sent.
        '400':
           description: Bad request. Invalid format.
        '415':
           description: The request body mimetype is not application/json.
    delete:
      tags:
        - Delete
      summary: Remove matching flows from all known datapaths.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/v2/flows/{dpid}':
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from a single datapath.
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
        '404':
          description: Datapath not found.
    post:
      tags:
        - Add
      summary: Insert flows in a single datapath.
      requestBody:
        description: List of flows to be inserted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
           type: string
          description: DPID of the target datapath.
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.
    delete:
      tags:
        - Delete
      summary: Remove matching flows from a single datapath.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.
  /api/kytos/flow_manager/v2/stored_flows:
    get:
      tags:
        - List
      summary: Retrieve a list of stored flows.
      parameters:
        - name: dpid
          schema:
            type: array
            items:
              type: string
          description: List of switch ids
          required: false
          in: query
          example: ["00:00:00:00:00:00:00:01","00:00:00:00:00:00:00:02"]
        - name: state
          in: query
          schema:
            type: string
          description: State of the flows to retrieve.
          required: false
          example: "installed"
        - name: cookie_range
          in: query
          schema:
            type: array
            items:
              type: integer
          description: Range of cookies
          required: false
          example: [84114963, 84114965]
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  switch: 
                    type: array
                    items:
                      $ref: '#/components/schemas/FlowDoc'
        '404':
          description: Path not found.
        '400':
          description: cookie_range only accepts exactly two values.
  /api/kytos/flow_manager/v2/delete:
    post:
      tags:
        - Delete
      summary: Remove matching flows from all known datapaths.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                flows:
                  type: array
                  items:
                    $ref: '#/components/schemas/Flow'
      deprecated: true
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/v2/delete/{dpid}':
    post:
      tags:
        - Delete
      summary: Remove matching flows from a single datapath.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                flows:
                  type: array
                  items:
                    $ref: '#/components/schemas/Flow'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      deprecated: true
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.

components:
  schemas:
    Match:
      type: object
      properties:
        in_port:
          type: integer
          format: int16
          example: 2
        dl_src:
          type: string
          example: '00:1f:3a:3e:9a:cf'
        dl_dst:
          type: string
          example: '00:15:af:d5:38:98'
        dl_type:
          type: integer
          format: int16
          example: 2048
        dl_vlan:
          type: integer
          format: int16
          example: 300
        dl_vlan_pcp:
          type: integer
          format: int8
          example: 0
        nw_src:
          type: string
          example: '192.168.0.1'
        nw_dst:
          type: string
          example: '192.168.0.2'
        nw_proto:
          type: integer
          format: int8
          example: 17
    Actions:
      type: array
      items:
        type: object
        properties:
          action_type:
            type: string
            enum: [set_vlan, output]
            example: 'output'
          value:
            type: integer
            format: int16
            example: 7
      example:
      - {
          "action_type": "output",
          "port": 42
        }
      - {
          "action_type": "set_vlan",
          "vlan_id": 42
        }
    Flow:
      type: object
      properties:
        priority:
          type: integer
          format: int16
          example: 10
        idle_timeout:
          type: integer
          format: int16
          example: 360
        hard_timeout:
          type: integer
          format: int16
          example: 1200
        cookie:
          type: integer
          format: int64
          example: 84114904
        match:
          $ref: '#/components/schemas/Match'
        actions:
          $ref: '#/components/schemas/Actions'
    Flows:
      type: object
      properties:
        '00:00:00:00:00:00:00:01':
          type: object
          properties:
            flows:
              type: array
              items:
                $ref: '#/components/schemas/Flow'
    FlowsBody:
      type: object
      properties:
        flows:
          type: array
          items:
            $ref: '#/components/schemas/Flow'
        force:
          type: boolean
          description: The force option is for ignoring switch connection errors, and delegating the flows to be automatically sent later on via consistency check.
          default: false
    FlowDoc:
      type: object
      properties:
        id:
          type: string
        switch:
          type: string
        flow_id:
          type: string
        state:
          type: string
        updated_at:
          type: string
        flow: 
          type: object
          items:
            $ref: '#/components/schemas/Flow'
