openapi: '3.0.0'
info:
  title: kytos/flow_manager
  version: 1.1.0
  description: >-
    **Warning**: *This documentation is experimental and may change soon.*


    Manages flows for OpenFlow switches, for version 1.3. Can add, list
    and remove flows from datapaths. Currently supports a subset of available
    matches and actions from the OpenFlow specification.
tags:
  - name: List
  - name: Add
  - name: Delete
paths:
  /api/kytos/flow_manager/v2/flows:
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from all known datapaths.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
        '404':
          description: Switch ID not found.
    post:
      tags:
        - Add
      summary: Insert flows in all known datapaths.
      requestBody:
        description: List of flows to be inserted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      responses:
        '202':
           description: FlowMod messages sent.
        '400':
           description: Bad request. Invalid format.
        '415':
           description: The request body mimetype is not application/json.
    delete:
      tags:
        - Delete
      summary: Remove matching flows from all known datapaths.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/v2/flows/{dpid}':
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from a single datapath.
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
        '404':
          description: Datapath not found.
    post:
      tags:
        - Add
      summary: Insert flows in a single datapath.
      requestBody:
        description: List of flows to be inserted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
           type: string
          description: DPID of the target datapath.
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.
    delete:
      tags:
        - Delete
      summary: Remove matching flows from a single datapath.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlowsBody'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.
  /api/kytos/flow_manager/v2/stored_flows:
    get:
      tags:
        - List
      summary: Retrieve a list of stored flows.
      parameters:
        - name: dpid
          schema:
            type: array
            items:
              type: string
          description: List of switch ids
          required: false
          in: query
          example: ["00:00:00:00:00:00:00:01","00:00:00:00:00:00:00:02"]
        - name: state
          in: query
          schema:
            type: array
            items:
              type: string
          description: List of states to retrieve
          required: false
          example: ["installed"]
        - name: cookie_range
          in: query
          schema:
            type: array
            items:
              type: integer
          description: Inclusive range of cookies. The length of the list must be even, for example, [1, 2, 5, 6], would include from 1 to 2 and from 5 to 6.
          required: false
          example: [84114963, 84114965]
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  switch: 
                    type: array
                    items:
                      $ref: '#/components/schemas/FlowDoc'
        '404':
          description: Path not found.
        '400':
          description: cookie_range only accepts exactly two values.
  /api/kytos/flow_manager/v2/delete:
    post:
      tags:
        - Delete
      summary: Remove matching flows from all known datapaths.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                flows:
                  type: array
                  items:
                    $ref: '#/components/schemas/Flow'
      deprecated: true
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/v2/delete/{dpid}':
    post:
      tags:
        - Delete
      summary: Remove matching flows from a single datapath.
      requestBody:
        description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                flows:
                  type: array
                  items:
                    $ref: '#/components/schemas/Flow'
      parameters:
        - name: dpid
          in: path
          required: true
          schema:
            type: string
          description: DPID of the target datapath.
      deprecated: true
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.

components:
  schemas:
    Match:
      type: object
      properties:
        in_port:
          type: integer
          format: int16
          example: 2
        dl_src:
          type: string
          example: '00:1f:3a:3e:9a:cf'
        dl_dst:
          type: string
          example: '00:15:af:d5:38:98'
        dl_type:
          type: integer
          format: int16
          example: 2048
        dl_vlan:
          oneOf:
            - type: string
              example: "40/4088"
            - type: integer
              example: 40
        dl_vlan_pcp:
          type: integer
          format: int8
          example: 0
        nw_src:
          type: string
          example: '192.168.0.1'
        nw_dst:
          type: string
          example: '192.168.0.2'
        nw_proto:
          type: integer
          format: int8
          example: 17
    Actions:
      type: array
      items:
        type: object
        properties:
          action_type:
            type: string
            enum: [set_vlan, output]
            example: 'output'
          value:
            type: integer
            format: int16
            example: 7
      example:
      - {
          "action_type": "output",
          "port": 42
        }
      - {
          "action_type": "set_vlan",
          "vlan_id": 42
        }
    Flow:
      type: object
      properties:
        priority:
          type: integer
          format: int16
          example: 10
        idle_timeout:
          type: integer
          format: int16
          example: 360
        hard_timeout:
          type: integer
          format: int16
          example: 1200
        cookie:
          type: integer
          format: int64
          example: 84114904
        match:
          $ref: '#/components/schemas/Match'
        actions:
          $ref: '#/components/schemas/Actions'
    Flows:
      type: object
      properties:
        '00:00:00:00:00:00:00:01':
          type: object
          properties:
            flows:
              type: array
              items:
                $ref: '#/components/schemas/Flow'
    FlowsBody:
      type: object
      properties:
        flows:
          type: array
          items:
            $ref: '#/components/schemas/Flow'
        force:
          type: boolean
          description: The force option is for ignoring switch connection errors, and delegating the flows to be automatically sent later on via consistency check.
          default: false
        batch_size:
          type: integer
          description: This is for batching, represents how many flows to send per iteration, every batch_interval seconds. If this value is zero it will send all at once. If you are sending many flows you probably want to use batching to potentially avoid overwhelming switches. Also, if the force option is true, then it will not block the request.
          minimum: 0
          default: 0
        batch_interval:
          type: integer
          description: The interval to wait for in seconds when sending a batch of flows.
          minimum: 0
          default: 0
    FlowDoc:
      type: object
      properties:
        id:
          type: string
        switch:
          type: string
        flow_id:
          type: string
        state:
          type: string
        updated_at:
          type: string
        flow: 
          type: object
          items:
            $ref: '#/components/schemas/Flow'
